// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package base

const TableNameSchemaPageDataName = "schema_page_data"

// SchemaPageData mapped from table <schema_page_data>
type SchemaPageData struct {
	SchemaPageDataID string  `gorm:"column:schema_page_data_id;primaryKey" json:"schema_page_data_id"`
	SchemaPageCode   *string `gorm:"column:schema_page_code" json:"schema_page_code"`
	ParentKey        *string `gorm:"column:parent_key" json:"parent_key"`
	Key              *string `gorm:"column:key" json:"key"`
	Value            *string `gorm:"column:value" json:"value"`
	BelongID         *string `gorm:"column:belong_id" json:"belong_id"`
	CreateTime       *string `gorm:"column:create_time" json:"create_time"`
	CreateUser       *string `gorm:"column:create_user" json:"create_user"`
	Index            *int32  `gorm:"column:index" json:"index"`
}

// TableName SchemaPageData's table name
func (*SchemaPageData) TableName() string {
	return TableNameSchemaPageDataName
}

func (*SchemaPageData) PrimaryKey() []string {
	return []string{"schema_page_data_id"}
}
