// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package base

const TableNameSchemaPageField = "schema_page_field"

type SchemaPageField struct {
	SchemaPageFieldID  string `gorm:"column:schema_page_field_id;primaryKey" json:"schema_page_field_id"`
	SchemaPageCode     string `gorm:"column:schema_page_code" json:"schema_page_code"`
	Name               string `gorm:"column:name" json:"name"`
	Key                string `gorm:"column:key" json:"key"`
	Type               string `gorm:"column:type" json:"type"`
	CreateTime         string `gorm:"column:create_time" json:"create_time"`
	CreateUser         string `gorm:"column:create_user" json:"create_user"`
	OrderIndex         string `gorm:"column:order_index" json:"order_index"`
	ParentKey          string `gorm:"column:parent_key" json:"parent_key"`
	BusinessGroup      string `gorm:"column:business_group" json:"business_group"`
	Description        string `gorm:"column:description" json:"description"`
	Tag                string `gorm:"column:tag" json:"tag"`
	Attr               string `gorm:"column:attr" json:"attr"`
	DataAttr           string `gorm:"column:data_attr" json:"data_attr"`
	Reg                string `gorm:"column:reg" json:"reg"`
	Link               string `gorm:"column:link" json:"link"`
	DataFrom           string `gorm:"column:data_from" json:"data_from"`
	Tip                string `gorm:"column:tip" json:"tip"`
	Value              string `gorm:"column:value" json:"value"`
	DemoTargetRowValue string `gorm:"column:demo_target_row_value" json:"demo_target_row_value"`
}

// TableName UserRoleIDList's table name
func (*SchemaPageField) TableName() string {
	return TableNameSchemaPageField
}

func (*SchemaPageField) PrimaryKey() []string {
	return []string{"schema_page_field_id"}
}
