INSERT INTO websql_recent_sql (
  recent_sql_id,
  project_code,
  recent_sql_hash,
  driver,
  connection_id,
  connection_name,
  statement_type,
  sql_text,
  execute_status,
  error_text,
  row_count,
  rows_affected,
  duration_ms,
  execute_count,
  last_executed_at,
  create_time,
  create_user,
  modify_time,
  modify_user
) VALUES (
  {{.recent_sql_id}},
  {{.project_code}},
  {{if .recent_sql_hash}}{{.recent_sql_hash}}{{else}}{{.recent_sql_id}}{{end}},
  {{if .driver}}{{.driver}}{{else}}''{{end}},
  {{if .connection_id}}{{.connection_id}}{{else}}''{{end}},
  {{if .connection_name}}{{.connection_name}}{{else}}''{{end}},
  {{if .statement_type}}{{.statement_type}}{{else}}''{{end}},
  {{.sql_text}},
  {{if .execute_status}}{{.execute_status}}{{else}}'success'{{end}},
  {{if .error_text}}{{.error_text}}{{else}}''{{end}},
  {{.row_count}},
  {{.rows_affected}},
  {{.duration_ms}},
  1,
  {{.last_executed_at}},
  {{.now_time}},
  {{if .session_user_id}}{{.session_user_id}}{{else}}''{{end}},
  {{.now_time}},
  {{if .session_user_id}}{{.session_user_id}}{{else}}''{{end}}
)
ON CONFLICT(recent_sql_id) DO UPDATE SET
  recent_sql_hash = excluded.recent_sql_hash,
  driver = excluded.driver,
  connection_id = excluded.connection_id,
  connection_name = excluded.connection_name,
  statement_type = excluded.statement_type,
  sql_text = excluded.sql_text,
  execute_status = excluded.execute_status,
  error_text = excluded.error_text,
  row_count = excluded.row_count,
  rows_affected = excluded.rows_affected,
  duration_ms = excluded.duration_ms,
  execute_count = COALESCE(websql_recent_sql.execute_count, 0) + 1,
  last_executed_at = excluded.last_executed_at,
  modify_time = excluded.modify_time,
  modify_user = excluded.modify_user;
