// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package autodesk

const TableNameDocProjectTask = "doc_project_task"

// WebshellToken mapped from table <webshell_token>
type DocProjectTask struct {
	DocProjectTaskID string  `gorm:"column:doc_project_task_id;primaryKey" json:"doc_project_task_id"` // ID
	DocProjectID     *string `gorm:"column:doc_project_id" json:"doc_project_id"`
	EventID          *string `gorm:"column:event_id" json:"event_id"` // 描述
	Status           *string `gorm:"column:status" json:"status"`
	CreateTime       *string `gorm:"column:create_time" json:"create_time"`
	FinishTime       *string `gorm:"column:finish_time" json:"finish_time"`
}

// TableName WebshellToken's table name
func (*DocProjectTask) TableName() string {
	return TableNameDocProjectTask
}

func (*DocProjectTask) PrimaryKey() []string {
	return []string{"doc_project_task_id"}
}
