// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package autodesk

const TableNameDocProjectContent = "doc_project_content"

// WebshellToken mapped from table <webshell_token>
type DocProjectContent struct {
	DocProjectContentID string  `gorm:"column:doc_project_content_id;primaryKey" json:"doc_project_content_id"` // ID
	DocProjectID        *string `gorm:"column:doc_project_id" json:"doc_project_id"`
	Group               *string `gorm:"column:group" json:"group"` // 描述
	DocContent          *string `gorm:"column:doc_content" json:"doc_content"`
	Topic               *string `gorm:"column:topic" json:"topic"`
	ParentID            *string `gorm:"column:parent_id" json:"parent_id"`
	OrderIndex          *int32  `gorm:"column:order_index" json:"order_index"`
}

// TableName WebshellToken's table name
func (*DocProjectContent) TableName() string {
	return TableNameDocProjectContent
}

func (*DocProjectContent) PrimaryKey() []string {
	return []string{"doc_project_content_id"}
}
