// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package autodesk

const TableNameDocProjectDetail = "doc_project_detail"

// WebshellToken mapped from table <webshell_token>
type DocProjectDetail struct {
	DocProjectDetailID string  `gorm:"column:doc_project_detail_id;primaryKey" json:"doc_project_detail_id"` // ID
	Code               *string `gorm:"column:code" json:"code"`                                              // 描述
	Name               *string `gorm:"column:name" json:"name"`                                              // 描述
	Detail             *string `gorm:"column:detail" json:"detail"`                                          // 描述
	Unit               *string `gorm:"column:unit" json:"unit"`                                              // 描述
	Spend              *string `gorm:"column:spend" json:"spend"`                                            // 描述
	DocProjectID       *string `gorm:"column:doc_project_id" json:"doc_project_id"`
	OrderIndex         *int32  `gorm:"column:order_index" json:"order_index"` // 描述
	Group              *int32  `gorm:"column:group" json:"group"`             // 描述
	ParentName         *string `gorm:"column:parent_name" json:"parent_name"` // 上级名称
	CreateTime         *string `gorm:"column:create_time" json:"create_time"` // datetime
	CreateUser         *string `gorm:"column:create_user" json:"create_user"` // 添加人

}

// TableName WebshellToken's table name
func (*DocProjectDetail) TableName() string {
	return TableNameDocProjectDetail
}

func (*DocProjectDetail) PrimaryKey() []string {
	return []string{"doc_project_detail_id"}
}
