// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package autodesk

const TableNameDocProject = "doc_project"

// WebshellToken mapped from table <webshell_token>
type DocProject struct {
	DocProjectID string  `gorm:"column:doc_project_id;primaryKey" json:"doc_project_id"` // ID
	Code         *string `gorm:"column:code" json:"code"`                                // 描述
	Name         *string `gorm:"column:name" json:"name"`                                // 描述
	Company      *string `gorm:"column:company" json:"company"`                          // 描述
	Address      *string `gorm:"column:address" json:"address"`                          // 描述
	TbProjectID  *string `gorm:"column:tb_project_id" json:"tb_project_id"`              // 描述
	CreateTime   *string `gorm:"column:create_time" json:"create_time"`                  // datetime
	CreateUser   *string `gorm:"column:create_user" json:"create_user"`                  // 添加人

}

// TableName WebshellToken's table name
func (*DocProject) TableName() string {
	return TableNameDocProject
}

func (*DocProject) PrimaryKey() []string {
	return []string{"doc_project_id"}
}
