// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package autodesk

const TableNameTbProjectManagerConfig = "tb_project_manager_config"

type TbProjectManagerConfig struct {
	TbProjectManagerConfigID string  `gorm:"column:tb_project_manager_config_id;primaryKey" json:"tb_project_manager_config_id"` // ID
	ProjectManager           *string `gorm:"column:project_manager" json:"project_manager"`                                      // 描述
	CreateTime               *string `gorm:"column:create_time" json:"create_time"`                                              // datetime
	CreateUser               *string `gorm:"column:create_user" json:"create_user"`                                              // 添加人

}

// TableName WebshellToken's table name
func (*TbProjectManagerConfig) TableName() string {
	return TableNameTbProjectManagerConfig
}

func (*TbProjectManagerConfig) PrimaryKey() []string {
	return []string{"tb_project_manager_config_id"}
}
