// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package doc

const FrontendDocGroupName = "frontend_doc_group"

type FrontendDocGroup struct {
	FrontendDocGroupID string  `gorm:"column:frontend_doc_group_id;primaryKey" json:"frontend_doc_group_id"`
	Name               *string `gorm:"column:name" json:"name"`               //
	Type               *string `gorm:"column:type" json:"type"`               //
	Code               *string `gorm:"column:code" json:"code"`               //
	Description        *string `gorm:"column:description" json:"description"` //
	OrderIndex         *int32  `gorm:"column:order_index" json:"order_index"`
	CreateTime         *string `gorm:"column:create_time" json:"create_time"`
	CreateUser         *string `gorm:"column:create_user" json:"create_user"`
	ParentID           *string `gorm:"column:parent_id" json:"parent_id"`
	BelongProject      *string `gorm:"column:belong_project" json:"belong_project"`
}

// TableName UserAccount's table name
func (*FrontendDocGroup) TableName() string {
	return FrontendDocGroupName
}

func (*FrontendDocGroup) PrimaryKey() []string {
	return []string{"frontend_doc_group_id"}
}
