// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package doc

const ImgName = "img"

type Img struct {
	ImgID      string  `gorm:"column:img_id;primaryKey" json:"img_id"`
	ImgDirID   string  `gorm:"column:img_dir_id" json:"img_dir_id"`
	Name       *string `gorm:"column:name" json:"name"` //
	CreateTime *string `gorm:"column:create_time" json:"create_time"`
	CreateUser *string `gorm:"column:create_user" json:"create_user"`
	Content    *string `gorm:"column:content" json:"content"`
	Path       *string `gorm:"column:path" json:"path"`
	Type       *string `gorm:"column:type" json:"type"`
}

func (*Img) TableName() string {
	return ImgName
}

func (*Img) PrimaryKey() []string {
	return []string{"img_id"}
}
